# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        active.storage:
            adapter: 'aws'
            options:
                client: 'aws.client'
                bucket: '%env(default:s3.fallback.bucket:AWS_S3_BUCKET)%'
                prefix: 'images'
